[package]
name = "makepad-realtime"
version = "0.1.0"
edition = "2024"

[dependencies]
makepad-widgets = { git = "https://github.com/makepad/makepad", branch = "dev"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.22"